# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
addons:
  apt:
    packages:
    - openvpn

before_install:
- sudo openvpn path/to/conf.ovpn &>>openvpn-client.log &

language: r
r:
  - oldrel
  - release
  - devel

cache: packages
